[tasks."ui:install"]
script = '''
cd frontend
npm i
'''

[tasks."ui:dev"]
script = '''
cd frontend
npm run dev
'''

[tasks."ui:build"]
script = '''
cd frontend
npm run build
'''

[tasks."install:gen"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''

[tasks."gen:sui"]
script = '''
cd frontend/
bun run gen:sui
bun run lint
'''

[tasks."sui:build"]
script = '''
cd contract
sui move build
'''

[tasks."sui:deploy"]
script = '''
cd contract
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."sui:mint"]
script = '''
cd contract
PACKAGE=0x49485ac54a0a889a387bda7aede26b4bf22e4a4cd4a4f39dd6dab2af4f182164
sui client call \
    --package $PACKAGE \
    --module issuer \
    --function mint \
    --args \
        0x288ecf868475733935eff7a09b3b41676a606fee7c0d77bb3782cd2507c72547 \
        0x6 \
        "Mazda Drive NFT" \
        "Web3 Global Hackathon for Mazda" \
        "https://pbs.twimg.com/profile_images/1538981748478214144/EUjTgb0v_400x400.jpg" \
    --gas-budget 123456789 \
'''

[tasks."sui:like"]
script = '''
cd contract
PACKAGE=0x49485ac54a0a889a387bda7aede26b4bf22e4a4cd4a4f39dd6dab2af4f182164
sui client call \
    --package $PACKAGE \
    --module issuer \
    --function like \
    --args \
        0x82902f562d65709d5e68e4b94c6523f1ed0d34e5a406ef6fdda4db03dbc940b5 \
    --gas-budget 123456789
'''