[tasks."ui:install"]
script = '''
cd frontend
npm i
'''

[tasks."ui:dev"]
script = '''
cd frontend
npm run dev
'''

[tasks."ui:build"]
script = '''
cd frontend
npm run build
'''

[tasks."install:gen"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''

[tasks."gen:sui"]
script = '''
cd frontend/
npm run gen:sui
npm run lint
'''

[tasks."sui:build"]
script = '''
cd contract
sui move build
'''

[tasks."sui:deploy"]
script = '''
cd contract
sui client publish --gas-budget 123456789 --skip-dependency-verification
'''

[tasks."sui:mint"]
script = '''
cd contract
PACKAGE=0x7e57ad667daf1ba82d8cc82b583cce57a71f187fd47d2099271cbf28d8a0e07f
NFT_INDEX=0x7acecf98813826f3820366ec2ba8d38262fb29f679fc2c33dbc6629526ecb560
sui client call \
    --package $PACKAGE \
    --module issuer \
    --function mint \
    --args \
        $NFT_INDEX \
        0x6 \
        "Mazda Drive NFT" \
        "Web3 Global Hackathon for Mazda" \
        "https://pbs.twimg.com/profile_images/1538981748478214144/EUjTgb0v_400x400.jpg" \
    --gas-budget 123456789 \
'''

[tasks."sui:like"]
script = '''
cd contract
PACKAGE=0x7e57ad667daf1ba82d8cc82b583cce57a71f187fd47d2099271cbf28d8a0e07f
NFT_ID=0x3a8c4ef033de4d87c7774bd0542b4de174596f4f86aec65bce9d9d861c9b379c
sui client call \
    --package $PACKAGE \
    --module issuer \
    --function like \
    --args \
        $NFT_ID \
    --gas-budget 123456789
'''